/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWatchlistIndexRouteImport } from './routes/_app/watchlist/index'
import { Route as AppFavoritesIndexRouteImport } from './routes/_app/favorites/index'
import { Route as AppBrowseIndexRouteImport } from './routes/_app/browse/index'
import { Route as AppMovieMovieIdRouteImport } from './routes/_app/movie/$movieId'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWatchlistIndexRoute = AppWatchlistIndexRouteImport.update({
  id: '/watchlist/',
  path: '/watchlist/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFavoritesIndexRoute = AppFavoritesIndexRouteImport.update({
  id: '/favorites/',
  path: '/favorites/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBrowseIndexRoute = AppBrowseIndexRouteImport.update({
  id: '/browse/',
  path: '/browse/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMovieMovieIdRoute = AppMovieMovieIdRouteImport.update({
  id: '/movie/$movieId',
  path: '/movie/$movieId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/movie/$movieId': typeof AppMovieMovieIdRoute
  '/browse/': typeof AppBrowseIndexRoute
  '/favorites/': typeof AppFavoritesIndexRoute
  '/watchlist/': typeof AppWatchlistIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/movie/$movieId': typeof AppMovieMovieIdRoute
  '/browse': typeof AppBrowseIndexRoute
  '/favorites': typeof AppFavoritesIndexRoute
  '/watchlist': typeof AppWatchlistIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/movie/$movieId': typeof AppMovieMovieIdRoute
  '/_app/browse/': typeof AppBrowseIndexRoute
  '/_app/favorites/': typeof AppFavoritesIndexRoute
  '/_app/watchlist/': typeof AppWatchlistIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/movie/$movieId'
    | '/browse/'
    | '/favorites/'
    | '/watchlist/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/movie/$movieId' | '/browse' | '/favorites' | '/watchlist'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/movie/$movieId'
    | '/_app/browse/'
    | '/_app/favorites/'
    | '/_app/watchlist/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/watchlist/': {
      id: '/_app/watchlist/'
      path: '/watchlist'
      fullPath: '/watchlist/'
      preLoaderRoute: typeof AppWatchlistIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/favorites/': {
      id: '/_app/favorites/'
      path: '/favorites'
      fullPath: '/favorites/'
      preLoaderRoute: typeof AppFavoritesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/browse/': {
      id: '/_app/browse/'
      path: '/browse'
      fullPath: '/browse/'
      preLoaderRoute: typeof AppBrowseIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/movie/$movieId': {
      id: '/_app/movie/$movieId'
      path: '/movie/$movieId'
      fullPath: '/movie/$movieId'
      preLoaderRoute: typeof AppMovieMovieIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppMovieMovieIdRoute: typeof AppMovieMovieIdRoute
  AppBrowseIndexRoute: typeof AppBrowseIndexRoute
  AppFavoritesIndexRoute: typeof AppFavoritesIndexRoute
  AppWatchlistIndexRoute: typeof AppWatchlistIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppMovieMovieIdRoute: AppMovieMovieIdRoute,
  AppBrowseIndexRoute: AppBrowseIndexRoute,
  AppFavoritesIndexRoute: AppFavoritesIndexRoute,
  AppWatchlistIndexRoute: AppWatchlistIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
